"""
Django settings for _03_django_orm project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fmgtpl5p+$z&u00fwy5u84=#=4ypxihc^0hn564ll*2jm40o21'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'post',
    'product'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '_03_django_orm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '_03_django_orm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', # MySQL 데이터베이스 엔진
        'NAME': 'djangodb',     # 데이터베이스 이름
        'USER': 'django',       # DB 접속 계정
        'PASSWORD': 'django',   # DB 접속 비밀번호
        'HOST': '127.0.0.1',    # DB 주소
        'PORT': '3306',         # MySQL 포트 번호
        # 한글/이모지 저장을 위한 문자 인코딩
        'OPTIONS': {            
            'charset' : 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asit/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

### ORM 쿼리 로그 출력을 보기좋게 포맷팅
import sqlparse # SQL 쿼리를 파싱하여 조작/제어

class SQLFormatter:
    def format(self, record):
        if record.sql:
            formatted_sql = sqlparse.format(record.sql, reindent=True, keyword_case='upper')
            execution_time = getattr(record,'duration',0.0)
            return f"{formatted_sql}\n[Execution Time: {execution_time:.3f}]"
        return record.getMessage()

# 로그 전역 설정
LOGGING = {
    'version' :1,       # logging 설정 버전
    'disable_existiong_loggers' : False,        # 기존 로거 비활성화 여부
    'hadlers' : {
        'console':{
            'class' : 'logging.StreamHandler',  # 콘솔에 로그 출력
            'formatter' : 'custom_sql'          # costom_sql 포맷터 사용
        },
    },
    'formatters':{
        'custom_sqk':{
            '()' : SQLFormatter,        # 사용자 정의 포맷터 클래스 등록
        },
    },
    'loggers':{
        'django.db.backends':{
            'level':'DEBUG',
            'handler': ['console'],
        },
    },    
}   