"""
Django settings for _04_qna project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lt+%h#fkk*nqi+md)8_=a9c!+=#g@m#1kt%)_xmra5&(j6ozio'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

# 앱 등록
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'qna',
    'uauth'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '_04_qna.urls'

# 템플릿 경로 설정
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '_04_qna.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# 데이터베이스 설정
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # MySQL 데이터베이스 엔진
        'NAME': 'qnadb',      # 데이터베이스 이름
        'USER': 'django',        # DB 접속 계정
        'PASSWORD': 'django',    # DB 접속 비밀번호
        'HOST': '127.0.0.1',     # DB 주소
        'PORT': '3306',          # MySQL 포트 번호
        # 한글/이모지 저장을 위한 문자 인코딩
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

# 패스워드 설정
AUTH_PASSWORD_VALIDATORS = [
    {
        # 사용자 속성과 유사한 비밀번호 금지
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # 비밀번호 최소길이 설정
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 4}
    },
    # {
    #     # 흔한 비밀번호 금지
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     # 숫자로만 된 비밀번호 금지
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

# 프로젝트의 기본 언어를 한국어로 설정
LANGUAGE_CODE = 'ko-kr'

# 프로젝트의 기본 시간대를 서울로 설정
TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'  # 정적 파일에 접근할 기본 URL 경로
STATICFILES_DIRS = [BASE_DIR / 'static']  # 개발시 사용할 정적 파일 디렉토리 설정 


### ORM 쿼리 로그 출력을 보기좋게 포맷팅 #################################
import sqlparse  # SQL 쿼리를 파싱하여 조작/제어

class SQLFormatter:
    def format(self, record):
        if record.sql:   # SQL 로그가 존재하면
            formatted_sql = sqlparse.format(record.sql, reindent=True, keyword_case='upper')  # SQL 키워드 대문자로, 들여쓰기
            execution_time = getattr(record, 'duration', 0.0)  # record 내 duration 속성이 있으면 값 사용, 없으면 0.0
            return f"{formatted_sql}\n[Execution Time: {execution_time:.3f}]"
        return record.getMessage()  # 일반 로그는 메시지 그대로 반환

# 로그 전역설정
LOGGING = {
    'version': 1,  # logging 설정 버전
    'disable_existing_loggers': False,  # 기존 로거 비활성화 여부
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',  # 콘솔에 로그 출력
            'formatter': 'custom_sql'          # custom_sql 포맷터 사용
        },
    },
    'formatters': {
        'custom_sql': {
            '()': SQLFormatter,  # 사용자 정의 포맷터 클래스 등록
        },
    },
    'loggers': {
        'django.db.backends': {
            'level': 'DEBUG',        # DB 쿼리 로그를 debug 레벨로 출력
            'handler': ['console'],  # console 핸들러 사용
        },
    },
}
#####################################################################

# 로그인 후 리다이렉트 URL 설정 (기본값: /accounts/profile)
LOGIN_REDIRECT_URL = '/'  # 로그인 성공 후 메인페이지로 이동

# 파일 업로드 처리
import os  # 운영체제 경로 처리 모듈

MEDIA_URL = '/media/'  # 업로드 파일에 접근할 기본 URL
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # 실제 저장될 폴더 경로

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
